---
setup:
  -
    type: project
    name: magelib
    target: target
builds:
  - type: go
    ldflags: "-s -w -X main.version={{.Version}}"
    main: ./cmd/builder
    name: builder
    output: "builder{{.Ext}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - type: show
  - type: upx
    build: builder
  - type: tar
    builds:
      - builder
    compression: gzip
  - type: show
