---
setup:
  -
    type: project
    id: magelib
    target: target
builds:
  - type: go
    ldflags: "-s -w -X main.version={{.Version}}"
    main: ./cmd/builder
    id: builder
    output: "builder{{.Ext}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - type: show
  - type: upx
    builds:
      - builder
  - type: tar
    builds:
      - builder
    compression: gzip
    id: targz
  - type: checksum
    builds:
      - builder
    output: "{{.ProjectName}}-{{.Version}}-files-checksums.txt"
  - type: checksum
    id: buildchecksum
    builds:
      - targz
    output: "{{.ProjectName}}-{{.Version}}-checksums.txt"
publishes:
  - type: show
  - type: scp
    builds:
      - targz
      - buildchecksum
    target: staticfiles@remoteserver.com:/var/www/default/public
