style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/julian7/goshipdone
options:
  commits:
    filters:
      Type:
        - add
        - change
        - deprecate
        - remove
        - fix
        - security
  commit_groups:
    title_maps:
      add: Added
      change: Changed
      deprecate: Deprecated
      remove: Removed
      fix: Fixed
      security: Security
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
