package ctx

const (
	_ = iota
	// FormatRaw represents an artifact in its pristine format (eg. binary or ar archive)
	FormatRaw
	// FormatGZip represents an artifact in compressed format (eg. the raw format compressed with gzip)
	FormatGZip
	// FormatUPX represents an artifact compressed by UPX (self-uncompressing executable)
	FormatUPX
	// FormatTar represents an artifact put together into a TAR archive. It can be further compressed.
	FormatTar
	// FormatZip represents an artifact put together into a ZIP archive.
	FormatZip
)

type (
	// Artifacts is a slice of Artifact
	Artifacts []*Artifact

	// Artifact is a file generated by the build pipeline, which can
	// be further processed by later steps (eg. a build result put into
	// an archive)
	Artifact struct {
		Filename string
		Format   int
		Name     string
		OS       string
		Arch     string
	}
)

// Add registers a new artifact in Artifacts
func (arts *Artifacts) Add(format int, name, filename, os, arch string) {
	*arts = append(*arts, &Artifact{
		Format:   format,
		Name:     name,
		Filename: filename,
		OS:       os,
		Arch:     arch,
	})
}

// ByName searches artifacts by their build names
func (arts *Artifacts) ByName(name string) Artifacts {
	results := Artifacts{}
	for i := range *arts {
		if (*arts)[i].Name == name {
			results = append(results, (*arts)[i])
		}
	}
	return results
}
